FROM --platform=linux/amd64 node:24.3.0-slim AS builder
WORKDIR /app
COPY . .
ARG VITE_APP_BACKEND_ADDRESS
ENV VITE_APP_BACKEND_ADDRESS=$VITE_APP_BACKEND_ADDRESS
ARG REACT_APP_HOST_IP_ADDRESS
ARG REACT_APP_PORT
ENV REACT_APP_HOST_IP_ADDRESS=$REACT_APP_HOST_IP_ADDRESS
ENV REACT_APP_PORT=$REACT_APP_PORT

RUN npm install
RUN npm run build
FROM nginx:1.29-alpine-slim AS prod
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d
COPY env.sh /docker-entrypoint.d/env.sh
RUN chmod +x /docker-entrypoint.d/env.sh
#EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
