version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tabata
    volumes:
      - ./data:/var/lib/postgresql/data\
  web:
    build:
      context: ./iws-ui
    ports:
      - "3000:3000"
    container_name: iws-ui
    volumes:
      - ./iws-ui:/Users/iwsmac/Downloads/tools/js/react/iws-ui
      - /Users/iwsmac/Downloads/tools/js/react/iws-ui/node_modules
    depends_on:
      - db