server {
  listen 3000;
  root   /usr/share/nginx/html;
  index  index.html;
  etag on;
      #ssl_certificate     localhost.crt;
      #ssl_certificate_key localhost.key;
      #ssl_protocols       TLSv1.2 TLSv1.3;
      #ssl_ciphers         HIGH:!aNULL:!MD5;

  location / {
    try_files $uri $uri/ /index.html;
  }

  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
